### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by qhz991029** [Ruyi-Zha/r2_gaussian#51]
Hi,

First of all, thank you for the excellent work on this project!

I am currently using `xray-gaussian-rasterization-voxelization` as part of a Gaussian-splatting-based density reconstruction pipeline, which adopts an image formation model similar to X-ray rendering. However, I’ve encountered a persistent issue: after approximately 10,000 training steps, the following error occurs in the forward process of `rasterization.py`:

```
RuntimeError: CUDA error: an illegal memory access was encountered
```

When I enable `debug=True`, I consistently get an error message pointing to this file:
```
[CUDA ERROR] in /XXX/YYY/ZZZ/xray-gaussian-rasterization-voxelization/cuda_rasterizer/rasterizer_impl.cu
```

Strangely, when I save and later reload the forward pass arguments in `rasterization.py` using:

```python
args = torch.load("/PATH/TO/FILE/snapshot_fw_3.dump")
args = tuple(arg.cuda().requires_grad_(True) if isinstance(arg, torch.Tensor) else arg for arg in args)
print(args)
num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = (
    _C.rasterize_gaussians(*args)
)
```

the crash cannot be reproduced, and the function runs without any errors.

In the experiments above, I was using 100,000 gaussian, but if I decrease the number to 5000, the error no longer occurs.

Do you have any idea what might be causing this non-deterministic behavior?

Any insights or suggestions would be greatly appreciated!

Best regards,
Huaizhi Qu

**Comment by Ruyi-Zha** [comment]
Hi, I’ve encountered similar issues when building the code. Unfortunately, I haven’t been able to determine the exact cause either...

**Comment by qhz991029** [comment]
Hi,

Thank you for your rapid response. May I ask how did you solve the issue to run experiments? Is it possible to provide more information about the issue you met? I am trying to do more observation but still cannot find any clue.

**Comment by Ruyi-Zha** [comment]
I suspect the issue might be related to the value range, such as NaNs or Infs. You may check if the input of rasterization has some inf/nan values. You could try enabling `CUDA_LAUNCH_BLOCKING=1` and `torch.autograd.set_detect_anomaly(True)` to help identify the source of the error. Unfortunately, I don’t recall more details about this issue...

**Comment by qhz991029** [comment]
Thank you for the information!

**Comment by qhz991029** [comment]
Hi,

After trying your suggestion, I found the problem located in the backward process of rasterization. Would the issue have something to do with the parallel rasterization mode I am using?

Best regards,
Huaizhi Qu

**Comment by Ruyi-Zha** [comment]
Hi I also see similar issues in original 3DGS repo. You might try to see if they help.

https://github.com/graphdeco-inria/gaussian-splatting/issues/41#issuecomment-1752279620

**Comment by qhz991029** [comment]
Hi,

Thank you so much for the help with the previous issue. I solved it, and it is due to the scale initialization.

In the meantime, I wonder if there's a parallel mode dataset I can use? All the synthetic and real datasets are in real cone mode.

Best regards,
Huaizhi Qu

**Comment by Ruyi-Zha** [comment]
Hi, you may follow [this instruction](https://github.com/Ruyi-Zha/r2_gaussian/blob/main/data_generator/synthetic_dataset/README.md) to generate synthetic dataset by using `data_generator/synthetic_dataset/scanner/parallel_beam.yml` for `--scanner`. Unfortunately I do not find parallel mode real dataset.
